import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#121212",
  card: "#1e1e1e",
  cardHeader: "#252525",
  primary: "#4dabf7",
  infoBg: "#1c3d5a",
  accent: "#fab005",
  text: "#e0e0e0",
  textMuted: "#888",
  success: "#2f9e44",
  danger: "#e03131",
  border: "#3e3e3e",
  inputBg: "#2d2d2d",
};

export const presets = [
  { label: "0:30", min: "0", sec: "30" },
  { label: "1:00", min: "1", sec: "0" },
  { label: "1:30", min: "1", sec: "30" },
  { label: "2:00", min: "2", sec: "0" },
  { label: "3:00", min: "3", sec: "0" },
  { label: "5:00", min: "5", sec: "0" },
];

export const progressColor = (remainPct) => {
  if (remainPct > 50) return COLORS.success;
  if (remainPct > 20) return COLORS.accent;
  return COLORS.danger;
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  root: { paddingHorizontal: 15, paddingTop: 14, paddingBottom: 110 },
  centerWrap: { width: "100%", maxWidth: 500, alignSelf: "center" },
  h1: { color: COLORS.primary, fontWeight: "800", fontSize: 20, textAlign: "center" },
  sub: { color: "#555", textAlign: "center", marginBottom: 14, marginTop: 4, fontSize: 11 },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderLeftWidth: 6,
    borderLeftColor: "#444",
    marginBottom: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardHeader: {
    paddingHorizontal: 15,
    paddingVertical: 14,
    backgroundColor: COLORS.cardHeader,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  cardTitle: { color: COLORS.primary, fontWeight: "700", fontSize: 16 },
  row: { flexDirection: "row", gap: 8, alignItems: "center" },
  rowInline: { flexDirection: "row", gap: 8, alignItems: "center" },
  half: { flex: 1 },
  status: {
    fontSize: 11,
    backgroundColor: "#333",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    textTransform: "uppercase",
    overflow: "hidden",
  },
  tabs: { flexDirection: "row", gap: 5, marginBottom: 14 },
  tab: { flex: 1, backgroundColor: "#252525", borderWidth: 1, borderColor: "#3a3a3a", borderRadius: 7, paddingVertical: 8, alignItems: "center" },
  tabActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  tabText: { color: "#666", fontWeight: "700", fontSize: 11 },
  tabTextActive: { color: "#111" },
  input: { borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.inputBg, color: "white", borderRadius: 8, paddingVertical: 11, paddingHorizontal: 10, marginBottom: 12, flex: 1, fontSize: 17 },
  switchRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  banner: { backgroundColor: COLORS.infoBg, borderLeftWidth: 3, borderLeftColor: COLORS.primary, borderRadius: 6, paddingVertical: 9, paddingHorizontal: 12, marginBottom: 12 },
  bannerText: { color: "#d0ebff", fontSize: 13 },
  resultPanel: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#252525",
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    marginBottom: 8,
    borderTopWidth: 1,
    borderTopColor: "#2e2e2e",
  },
  small: { color: "#666", fontSize: 11 },
  timer: { color: COLORS.primary, fontSize: 22, fontWeight: "800", marginTop: 2, letterSpacing: 1 },
  progressBg: { height: 6, borderRadius: 4, backgroundColor: "#1a1a1a", overflow: "hidden", marginBottom: 10 },
  progressBar: { height: "100%", borderRadius: 4 },
  btn: { borderRadius: 8, paddingVertical: 13, paddingHorizontal: 8, alignItems: "center", justifyContent: "center", flex: 1 },
  smallBtn: { paddingVertical: 7, paddingHorizontal: 10, borderRadius: 8 },
  btnSuccess: { backgroundColor: COLORS.success },
  btnAccent: { backgroundColor: COLORS.accent },
  btnMuted: { backgroundColor: "#3a3f44" },
  btnText: { color: "white", fontWeight: "700", fontSize: 14 },
  btnTextDark: { color: "#111", fontWeight: "700", fontSize: 14 },
  deleteBtn: { width: 46, height: 46, borderRadius: 8, backgroundColor: "#3a1a1a", alignItems: "center", justifyContent: "center" },
  calcBtn: { width: 46, height: 46, borderRadius: 8, borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.inputBg, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  calcBox: { backgroundColor: "#1b2d1b", borderLeftColor: COLORS.success, borderLeftWidth: 3, borderRadius: 8, padding: 12, marginTop: 12, marginBottom: 8 },
  secondaryBtn: { backgroundColor: "#2a3a4a", borderWidth: 1, borderColor: "#2a4a6a", borderRadius: 8, paddingVertical: 10, alignItems: "center", marginTop: 8 },
  secondaryText: { color: COLORS.primary, fontWeight: "600", fontSize: 13 },
  note: { color: COLORS.text, fontSize: 12, lineHeight: 17 },
  presetRow: { flexDirection: "row", gap: 8, marginBottom: 8, flexWrap: "wrap" },
  presetBtn: { backgroundColor: "#2a3a4a", borderWidth: 1, borderColor: "#2a4a6a", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 6 },
  presetText: { color: COLORS.primary, fontWeight: "600", fontSize: 12 },
  historyItem: { borderBottomWidth: 1, borderBottomColor: "#2e2e2e", paddingVertical: 8 },
  fab: { position: "absolute", right: 20, bottom: 20, width: 58, height: 58, borderRadius: 29, backgroundColor: COLORS.primary, alignItems: "center", justifyContent: "center", shadowColor: COLORS.primary, shadowOpacity: 0.45, shadowRadius: 15, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
  modalWrap: { flex: 1, backgroundColor: "rgba(0,0,0,.85)", alignItems: "center", justifyContent: "center", padding: 20 },
  modalBody: { backgroundColor: "#252525", borderRadius: 14, padding: 18, width: "100%", maxWidth: 320 },
  calcDisplay: { backgroundColor: "#111", borderRadius: 8, color: "white", fontSize: 22, paddingHorizontal: 12, paddingVertical: 13, marginBottom: 13, textAlign: "right" },
  calcGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, justifyContent: "space-between" },
  cbtn: { width: "22%", borderRadius: 8, backgroundColor: "#333", alignItems: "center", justifyContent: "center", paddingVertical: 14 },
  // Новые стили для версии обновления
  versionText: { color: "#444", fontSize: 10, textAlign: "center", marginTop: 8 },
});
